### ISSUE TITLE
Badges & hierarchy position broken

### ISSUE THREAD

**Issue by floppydisk05** [nickandfloppy/NetRunner#10]
`whois` displays "None" for badges regardless of whether the user has any badges or not.

Also something about the "hierarchy position" being fucked up idk

(Issue on behalf of @dkay0670 because he's busy or something)

**Comment by dkay0670** [comment]
floppy is dumb, the bug is that badges has some random number or the text of some emote

**Comment by floppydisk05** [comment]
it's because it had custom emojis before but I have to reinvite it to the ihdsfjdg 

I'll look into it tomorrow
